[project]
name = "ji"
version = "0.1.0"
requires-python = ">=3.13"

[dependency-groups]
dev = []

[tool.ruff]
line-length = 100
lint.select = ["ALL"]
lint.ignore = ["D"]
lint.per-file-ignores = { "tests/**/*.py" = ["S101"] }
